# Generated by Django 5.2.8 on 2025-12-02 02:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0003_pesousuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pescoco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ombro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('biceps_e', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bíceps Esquerdo')),
                ('biceps_d', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Bíceps Direito')),
                ('antebraco_e', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Antebraço Esquerdo')),
                ('antebraco_d', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Antebraço Direito')),
                ('coxa_e', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Coxa Esquerda')),
                ('coxa_d', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Coxa Direita')),
                ('panturrilha_e', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Panturrilha Esquerda')),
                ('panturrilha_d', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Panturrilha Direita')),
                ('gordura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Gordura Corporal %')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
