# Generated by Django 5.2.8 on 2025-12-02 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0004_medidacorporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidacorporal',
            name='antebraco_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='antebraco_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='biceps_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='biceps_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='coxa_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='coxa_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='gordura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='panturrilha_d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medidacorporal',
            name='panturrilha_e',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
