# Generated by Django 5.2.8 on 2025-12-08 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0005_alter_medidacorporal_antebraco_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serierealizada',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
