# Generated by Django 5.2.8 on 2025-12-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0006_alter_serierealizada_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='grupo_muscular',
            field=models.CharField(choices=[('PEITO', 'Peitoral'), ('OMBRO_ANT', 'Deltoide Anterior'), ('OMBRO_LAT', 'Deltoide Lateral'), ('OMBRO_POST', 'Deltoide Posterior'), ('TRICEPS', 'Tríceps'), ('COSTAS', 'Dorsais'), ('TRAPEZIO', 'Trapézio'), ('BICEPS', 'Bíceps'), ('ANTEBRACO', 'Antebraço'), ('QUADRICEPS', 'Quadríceps'), ('POSTERIOR', 'Posterior de Coxa'), ('GLUTEOS', 'Glúteos'), ('PANTURRILHA', 'Panturrilhas'), ('ABS', 'Abdômen'), ('LOMBAR', 'Lombar'), ('CARDIO', 'Cardio')], max_length=20),
        ),
    ]
