# Generated by Django 5.2.8 on 2025-12-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0007_alter_exercicio_grupo_muscular'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotina',
            name='ordem_exercicios',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
