# Generated by Django 5.2.8 on 2025-12-17 14:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0009_treino'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('repeticoes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio')),
                ('metodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='treinos.metodo')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.treino')),
            ],
        ),
    ]
